name: deploy

on:

  push:

    branches:

      - main

      - master

  schedule:

    - cron: '0 0 * * *' # Everyday at 12am

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

 

      - name: connect to server

        uses: appleboy/ssh-action@master

        with:

          host: 192.168.41.5

          username: oracle

          password: aot@123

          port: 14800

          script: |

            mkdir -p /tmp/test
